In [ ]:
pip install scikit-learn
pip install pandas

In [29]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
df = pd.read_csv("movies.csv")
df

    age  gender        genre
0    35       1        Drama
1    31       1  Documentary
2    36       0        Drama
3    35       0     Thriller
4    41       1       Action
..  ...     ...          ...
95   41       1       Action
96   20       1  Documentary
97   31       0     Thriller
98   24       1       Action
99   24       0  Documentary

[100 rows x 3 columns]

In [30]:
df.shape

(100, 3)

In [31]:
df.describe()

              age  gender
count  100.000000  100.00
mean    32.100000    0.55
std      8.316346    0.50
min     18.000000    0.00
25%     25.000000    0.00
50%     31.000000    1.00
75%     40.000000    1.00
max     45.000000    1.00

In [ ]:
from sklearn.tree import DecisionTreeClassifier
df = pd.read_csv("movies.csv")
X = df.drop(columns=["genre"])

In [ ]:
df = pd.read_csv("movies.csv")
Y = df.drop(columns=["age","gender"])

In [35]:
model = DecisionTreeClassifier()
model.fit(X.values , Y.values)

prediction = model.predict([[22,1],[33,0]])
prediction

array(['Drama', 'Documentary'], dtype=object)

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
x_train , x_test ,y_train , y_test = train_test_split(X,Y,test_size=0.2)
model = DecisionTreeClassifier()
model.fit(x_train.values , y_train.values)

prediction = model.predict(x_test.values)
score = accuracy_score(y_test , prediction)
score

0.1

In [56]:
import joblib
joblib.dump(model ,"movie-recommender.joblib") # create a binary acceptable file
model = joblib.load("movie-recommender.joblib")

prediction =  model.predict([[29,0]])
prediction

array(['Documentary'], dtype=object)

In [64]:
#graps representation visually
import pandas as pd
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

moviedata = pd.read_csv("movies.csv")
X = moviedata.drop(columns=["genre"])
Y = moviedata["genre"]

model = DecisionTreeClassifier()
model.fit(X.values , Y.values)

tree.export_graphviz(model , out_file = "movie-recommender.dot" , feature_names=["age" , "gender"] , class_names= sorted(Y.unique()),label = "all" , rounded = True , filled=True )